package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BASE_SYNC_DTO.
 */
public class BaseSyncDTO {

    private Long id;
    private Long ServerId;
    private String RowId;

    // KEEP FIELDS - put your custom fields here
    public static final String SERVER_ID_COLUMNNAME = "ServerId";
    public static final String UUID_COLUMNNAME = "RowId";
    // KEEP FIELDS END

    public BaseSyncDTO() {
    }

    public BaseSyncDTO(Long id) {
        this.id = id;
    }

    public BaseSyncDTO(Long id, Long ServerId, String RowId) {
        this.id = id;
        this.ServerId = ServerId;
        this.RowId = RowId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return ServerId;
    }

    public void setServerId(Long ServerId) {
        this.ServerId = ServerId;
    }

    public String getRowId() {
        return RowId;
    }

    public void setRowId(String RowId) {
        this.RowId = RowId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
