package com.health.data;

import com.health.data.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblbodyfeeling.
 */
public class BodyFeeling implements IFeeling {

    private Long id;
    private Long ServerId;
    private String RowId;
    private Long UserId;
    private Integer X;
    private Integer Y;
    private java.util.Date StartDate;
    private Long FeelingTypeId;
    private Long CustomFeelingTypeId;
    private Long BodyRegionId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient BodyFeelingDao myDao;

    private BodyFeelingType bodyFeelingType;
    private Long bodyFeelingType__resolvedKey;

    private CustomBodyFeelingType customBodyFeelingType;
    private Long customBodyFeelingType__resolvedKey;

    private BodyRegion bodyRegion;
    private Long bodyRegion__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    public static final String BODY_FEELING_TYPE_COLUMN_NAME = "feelingtypeid";
    public static final String CUSTOM_BODY_FEELING_TYPE_COLUMN_NAME = "customfeelingtypeid";
    public static final String START_DATE_COLUMN_NAME = "StartDate";
    public static final String BODY_REGION_COLUMN_NAME = "bodyregionid";
    
    
    public Long BodyFeelingTypeServerId;
    public Long CustomBodyFeelingTypeServerId;
    public int OperationTypeId;    
    // KEEP FIELDS END

    public BodyFeeling() {
    }

    public BodyFeeling(Long id) {
        this.id = id;
    }

    public BodyFeeling(Long id, Long ServerId, String RowId, Long UserId, Integer X, Integer Y, java.util.Date StartDate, Long FeelingTypeId, Long CustomFeelingTypeId, Long BodyRegionId) {
        this.id = id;
        this.ServerId = ServerId;
        this.RowId = RowId;
        this.UserId = UserId;
        this.X = X;
        this.Y = Y;
        this.StartDate = StartDate;
        this.FeelingTypeId = FeelingTypeId;
        this.CustomFeelingTypeId = CustomFeelingTypeId;
        this.BodyRegionId = BodyRegionId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBodyFeelingDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return ServerId;
    }

    public void setServerId(Long ServerId) {
        this.ServerId = ServerId;
    }

    public String getRowId() {
        return RowId;
    }

    public void setRowId(String RowId) {
        this.RowId = RowId;
    }

    public Long getUserId() {
        return UserId;
    }

    public void setUserId(Long UserId) {
        this.UserId = UserId;
    }

    public Integer getX() {
        return X;
    }

    public void setX(Integer X) {
        this.X = X;
    }

    public Integer getY() {
        return Y;
    }

    public void setY(Integer Y) {
        this.Y = Y;
    }

    public java.util.Date getStartDate() {
        return StartDate;
    }

    public void setStartDate(java.util.Date StartDate) {
        this.StartDate = StartDate;
    }

    public Long getFeelingTypeId() {
        return FeelingTypeId;
    }

    public void setFeelingTypeId(Long FeelingTypeId) {
        this.FeelingTypeId = FeelingTypeId;
    }

    public Long getCustomFeelingTypeId() {
        return CustomFeelingTypeId;
    }

    public void setCustomFeelingTypeId(Long CustomFeelingTypeId) {
        this.CustomFeelingTypeId = CustomFeelingTypeId;
    }

    public Long getBodyRegionId() {
        return BodyRegionId;
    }

    public void setBodyRegionId(Long BodyRegionId) {
        this.BodyRegionId = BodyRegionId;
    }

    /** To-one relationship, resolved on first access. */
    public BodyFeelingType getBodyFeelingType() {
        Long __key = this.FeelingTypeId;
        if (bodyFeelingType__resolvedKey == null || !bodyFeelingType__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BodyFeelingTypeDao targetDao = daoSession.getBodyFeelingTypeDao();
            BodyFeelingType bodyFeelingTypeNew = targetDao.load(__key);
            synchronized (this) {
                bodyFeelingType = bodyFeelingTypeNew;
            	bodyFeelingType__resolvedKey = __key;
            }
        }
        return bodyFeelingType;
    }

    public void setBodyFeelingType(BodyFeelingType bodyFeelingType) {
        synchronized (this) {
            this.bodyFeelingType = bodyFeelingType;
            FeelingTypeId = bodyFeelingType == null ? null : bodyFeelingType.getId();
            bodyFeelingType__resolvedKey = FeelingTypeId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public CustomBodyFeelingType getCustomBodyFeelingType() {
        Long __key = this.CustomFeelingTypeId;
        if (customBodyFeelingType__resolvedKey == null || !customBodyFeelingType__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CustomBodyFeelingTypeDao targetDao = daoSession.getCustomBodyFeelingTypeDao();
            CustomBodyFeelingType customBodyFeelingTypeNew = targetDao.load(__key);
            synchronized (this) {
                customBodyFeelingType = customBodyFeelingTypeNew;
            	customBodyFeelingType__resolvedKey = __key;
            }
        }
        return customBodyFeelingType;
    }

    public void setCustomBodyFeelingType(CustomBodyFeelingType customBodyFeelingType) {
        synchronized (this) {
            this.customBodyFeelingType = customBodyFeelingType;
            CustomFeelingTypeId = customBodyFeelingType == null ? null : customBodyFeelingType.getId();
            customBodyFeelingType__resolvedKey = CustomFeelingTypeId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public BodyRegion getBodyRegion() {
        Long __key = this.BodyRegionId;
        if (bodyRegion__resolvedKey == null || !bodyRegion__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BodyRegionDao targetDao = daoSession.getBodyRegionDao();
            BodyRegion bodyRegionNew = targetDao.load(__key);
            synchronized (this) {
                bodyRegion = bodyRegionNew;
            	bodyRegion__resolvedKey = __key;
            }
        }
        return bodyRegion;
    }

    public void setBodyRegion(BodyRegion bodyRegion) {
        synchronized (this) {
            this.bodyRegion = bodyRegion;
            BodyRegionId = bodyRegion == null ? null : bodyRegion.getId();
            bodyRegion__resolvedKey = BodyRegionId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String getName() {
        return String.format("%s: %s", this.getBodyRegion().getName(), this.getBodyFeelingType() != null ? this.getBodyFeelingType().getName() : this.getCustomBodyFeelingType().getName());
    }

    @Override
    public Double getValue1() {
        return null;
    }

    @Override
    public Double getValue2() {
        return null;
    }

    @Override
    public Double getValue3() {
        return null;
    }
    // KEEP METHODS END

}
