package com.health.data;

import com.health.data.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblbodyregion.
 */
public class BodyRegion implements IDictionaryDTO {

    private Long id;
    private String name;
    private String FullName;
    private Long BodyComplaintTypeId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient BodyRegionDao myDao;

    private BodyComplaintType bodyComplaintType;
    private Long bodyComplaintType__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BodyRegion() {
    }

    public BodyRegion(Long id) {
        this.id = id;
    }

    public BodyRegion(Long id, String name, String FullName, Long BodyComplaintTypeId) {
        this.id = id;
        this.name = name;
        this.FullName = FullName;
        this.BodyComplaintTypeId = BodyComplaintTypeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBodyRegionDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFullName() {
        return FullName;
    }

    public void setFullName(String FullName) {
        this.FullName = FullName;
    }

    public Long getBodyComplaintTypeId() {
        return BodyComplaintTypeId;
    }

    public void setBodyComplaintTypeId(Long BodyComplaintTypeId) {
        this.BodyComplaintTypeId = BodyComplaintTypeId;
    }

    /** To-one relationship, resolved on first access. */
    public BodyComplaintType getBodyComplaintType() {
        Long __key = this.BodyComplaintTypeId;
        if (bodyComplaintType__resolvedKey == null || !bodyComplaintType__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BodyComplaintTypeDao targetDao = daoSession.getBodyComplaintTypeDao();
            BodyComplaintType bodyComplaintTypeNew = targetDao.load(__key);
            synchronized (this) {
                bodyComplaintType = bodyComplaintTypeNew;
            	bodyComplaintType__resolvedKey = __key;
            }
        }
        return bodyComplaintType;
    }

    public void setBodyComplaintType(BodyComplaintType bodyComplaintType) {
        synchronized (this) {
            this.bodyComplaintType = bodyComplaintType;
            BodyComplaintTypeId = bodyComplaintType == null ? null : bodyComplaintType.getId();
            bodyComplaintType__resolvedKey = BodyComplaintTypeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
