package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Locale;
// KEEP INCLUDES END
/**
 * Entity mapped to table tblcountry.
 */
public class Country {

    private Long id;
    private String name;
    private String Code;
    private String Culture;
    private String Name_ru;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Country() {
    }

    public Country(Long id) {
        this.id = id;
    }

    public Country(Long id, String name, String Code, String Culture, String Name_ru) {
        this.id = id;
        this.name = name;
        this.Code = Code;
        this.Culture = Culture;
        this.Name_ru = Name_ru;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    public String getCulture() {
        return Culture;
    }

    public void setCulture(String Culture) {
        this.Culture = Culture;
    }

    public String getName_ru() {
        return Name_ru;
    }

    public void setName_ru(String Name_ru) {
        this.Name_ru = Name_ru;
    }

    // KEEP METHODS - put your custom methods here
    public String getName(Locale locale){
    	if(this.Name_ru != null && locale.getCountry().equalsIgnoreCase("RU") || locale.getCountry().equalsIgnoreCase("UA") || locale.getCountry().equalsIgnoreCase("BY")){
    		return this.Name_ru;
    	}
    	return name;
    }
    // KEEP METHODS END

}
