package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblkpindex.
 */
public class KpIndex implements IDictionaryDTO {

    private Long id;
    private Integer IntValue;
    private String StrValue;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public KpIndex() {
    }

    public KpIndex(Long id) {
        this.id = id;
    }

    public KpIndex(Long id, Integer IntValue, String StrValue) {
        this.id = id;
        this.IntValue = IntValue;
        this.StrValue = StrValue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIntValue() {
        return IntValue;
    }

    public void setIntValue(Integer IntValue) {
        this.IntValue = IntValue;
    }

    public String getStrValue() {
        return StrValue;
    }

    public void setStrValue(String StrValue) {
        this.StrValue = StrValue;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String getName() {
        return this.StrValue;
    }
    // KEEP METHODS END

}
