package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblmoon.
 */
public class Moon {

    private Long id;
    private Long ServerId;
    private String RowId;
    private java.util.Date InfoDate;
    private Double MoonVisibility;
    private java.util.Date MoonOld;
    private java.util.Date MoonRise;
    private java.util.Date MoonSet;
    private Integer MoonPhaseId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Moon() {
    }

    public Moon(Long id) {
        this.id = id;
    }

    public Moon(Long id, Long ServerId, String RowId, java.util.Date InfoDate, Double MoonVisibility, java.util.Date MoonOld, java.util.Date MoonRise, java.util.Date MoonSet, Integer MoonPhaseId) {
        this.id = id;
        this.ServerId = ServerId;
        this.RowId = RowId;
        this.InfoDate = InfoDate;
        this.MoonVisibility = MoonVisibility;
        this.MoonOld = MoonOld;
        this.MoonRise = MoonRise;
        this.MoonSet = MoonSet;
        this.MoonPhaseId = MoonPhaseId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return ServerId;
    }

    public void setServerId(Long ServerId) {
        this.ServerId = ServerId;
    }

    public String getRowId() {
        return RowId;
    }

    public void setRowId(String RowId) {
        this.RowId = RowId;
    }

    public java.util.Date getInfoDate() {
        return InfoDate;
    }

    public void setInfoDate(java.util.Date InfoDate) {
        this.InfoDate = InfoDate;
    }

    public Double getMoonVisibility() {
        return MoonVisibility;
    }

    public void setMoonVisibility(Double MoonVisibility) {
        this.MoonVisibility = MoonVisibility;
    }

    public java.util.Date getMoonOld() {
        return MoonOld;
    }

    public void setMoonOld(java.util.Date MoonOld) {
        this.MoonOld = MoonOld;
    }

    public java.util.Date getMoonRise() {
        return MoonRise;
    }

    public void setMoonRise(java.util.Date MoonRise) {
        this.MoonRise = MoonRise;
    }

    public java.util.Date getMoonSet() {
        return MoonSet;
    }

    public void setMoonSet(java.util.Date MoonSet) {
        this.MoonSet = MoonSet;
    }

    public Integer getMoonPhaseId() {
        return MoonPhaseId;
    }

    public void setMoonPhaseId(Integer MoonPhaseId) {
        this.MoonPhaseId = MoonPhaseId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
