package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblparticle.
 */
public class Particle {

    private Long id;
    private Long ServerId;
    private String RowId;
    private java.util.Date InfoDate;
    private Long Proton1MeV;
    private Long Proton10MeV;
    private Long Proton100MeV;
    private Long Electron08MeV;
    private Long Electron2MeV;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Particle() {
    }

    public Particle(Long id) {
        this.id = id;
    }

    public Particle(Long id, Long ServerId, String RowId, java.util.Date InfoDate, Long Proton1MeV, Long Proton10MeV, Long Proton100MeV, Long Electron08MeV, Long Electron2MeV) {
        this.id = id;
        this.ServerId = ServerId;
        this.RowId = RowId;
        this.InfoDate = InfoDate;
        this.Proton1MeV = Proton1MeV;
        this.Proton10MeV = Proton10MeV;
        this.Proton100MeV = Proton100MeV;
        this.Electron08MeV = Electron08MeV;
        this.Electron2MeV = Electron2MeV;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return ServerId;
    }

    public void setServerId(Long ServerId) {
        this.ServerId = ServerId;
    }

    public String getRowId() {
        return RowId;
    }

    public void setRowId(String RowId) {
        this.RowId = RowId;
    }

    public java.util.Date getInfoDate() {
        return InfoDate;
    }

    public void setInfoDate(java.util.Date InfoDate) {
        this.InfoDate = InfoDate;
    }

    public Long getProton1MeV() {
        return Proton1MeV;
    }

    public void setProton1MeV(Long Proton1MeV) {
        this.Proton1MeV = Proton1MeV;
    }

    public Long getProton10MeV() {
        return Proton10MeV;
    }

    public void setProton10MeV(Long Proton10MeV) {
        this.Proton10MeV = Proton10MeV;
    }

    public Long getProton100MeV() {
        return Proton100MeV;
    }

    public void setProton100MeV(Long Proton100MeV) {
        this.Proton100MeV = Proton100MeV;
    }

    public Long getElectron08MeV() {
        return Electron08MeV;
    }

    public void setElectron08MeV(Long Electron08MeV) {
        this.Electron08MeV = Electron08MeV;
    }

    public Long getElectron2MeV() {
        return Electron2MeV;
    }

    public void setElectron2MeV(Long Electron2MeV) {
        this.Electron2MeV = Electron2MeV;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
