package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblplanet.
 */
public class Planet {

    private Long id;
    private Long ServerId;
    private String RowId;
    private java.util.Date InfoDate;
    private java.util.Date MercuryRise;
    private java.util.Date MercurySet;
    private java.util.Date VenusRise;
    private java.util.Date VenusSet;
    private java.util.Date MarsRise;
    private java.util.Date MarsSet;
    private java.util.Date JupiterRise;
    private java.util.Date JupiterSet;
    private java.util.Date SaturnRise;
    private java.util.Date SaturnSet;
    private java.util.Date UranusRise;
    private java.util.Date UranusSet;
    private java.util.Date NeptuneRise;
    private java.util.Date NeptuneSet;
    private java.util.Date PlutoRise;
    private java.util.Date PlutoSet;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Planet() {
    }

    public Planet(Long id) {
        this.id = id;
    }

    public Planet(Long id, Long ServerId, String RowId, java.util.Date InfoDate, java.util.Date MercuryRise, java.util.Date MercurySet, java.util.Date VenusRise, java.util.Date VenusSet, java.util.Date MarsRise, java.util.Date MarsSet, java.util.Date JupiterRise, java.util.Date JupiterSet, java.util.Date SaturnRise, java.util.Date SaturnSet, java.util.Date UranusRise, java.util.Date UranusSet, java.util.Date NeptuneRise, java.util.Date NeptuneSet, java.util.Date PlutoRise, java.util.Date PlutoSet) {
        this.id = id;
        this.ServerId = ServerId;
        this.RowId = RowId;
        this.InfoDate = InfoDate;
        this.MercuryRise = MercuryRise;
        this.MercurySet = MercurySet;
        this.VenusRise = VenusRise;
        this.VenusSet = VenusSet;
        this.MarsRise = MarsRise;
        this.MarsSet = MarsSet;
        this.JupiterRise = JupiterRise;
        this.JupiterSet = JupiterSet;
        this.SaturnRise = SaturnRise;
        this.SaturnSet = SaturnSet;
        this.UranusRise = UranusRise;
        this.UranusSet = UranusSet;
        this.NeptuneRise = NeptuneRise;
        this.NeptuneSet = NeptuneSet;
        this.PlutoRise = PlutoRise;
        this.PlutoSet = PlutoSet;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return ServerId;
    }

    public void setServerId(Long ServerId) {
        this.ServerId = ServerId;
    }

    public String getRowId() {
        return RowId;
    }

    public void setRowId(String RowId) {
        this.RowId = RowId;
    }

    public java.util.Date getInfoDate() {
        return InfoDate;
    }

    public void setInfoDate(java.util.Date InfoDate) {
        this.InfoDate = InfoDate;
    }

    public java.util.Date getMercuryRise() {
        return MercuryRise;
    }

    public void setMercuryRise(java.util.Date MercuryRise) {
        this.MercuryRise = MercuryRise;
    }

    public java.util.Date getMercurySet() {
        return MercurySet;
    }

    public void setMercurySet(java.util.Date MercurySet) {
        this.MercurySet = MercurySet;
    }

    public java.util.Date getVenusRise() {
        return VenusRise;
    }

    public void setVenusRise(java.util.Date VenusRise) {
        this.VenusRise = VenusRise;
    }

    public java.util.Date getVenusSet() {
        return VenusSet;
    }

    public void setVenusSet(java.util.Date VenusSet) {
        this.VenusSet = VenusSet;
    }

    public java.util.Date getMarsRise() {
        return MarsRise;
    }

    public void setMarsRise(java.util.Date MarsRise) {
        this.MarsRise = MarsRise;
    }

    public java.util.Date getMarsSet() {
        return MarsSet;
    }

    public void setMarsSet(java.util.Date MarsSet) {
        this.MarsSet = MarsSet;
    }

    public java.util.Date getJupiterRise() {
        return JupiterRise;
    }

    public void setJupiterRise(java.util.Date JupiterRise) {
        this.JupiterRise = JupiterRise;
    }

    public java.util.Date getJupiterSet() {
        return JupiterSet;
    }

    public void setJupiterSet(java.util.Date JupiterSet) {
        this.JupiterSet = JupiterSet;
    }

    public java.util.Date getSaturnRise() {
        return SaturnRise;
    }

    public void setSaturnRise(java.util.Date SaturnRise) {
        this.SaturnRise = SaturnRise;
    }

    public java.util.Date getSaturnSet() {
        return SaturnSet;
    }

    public void setSaturnSet(java.util.Date SaturnSet) {
        this.SaturnSet = SaturnSet;
    }

    public java.util.Date getUranusRise() {
        return UranusRise;
    }

    public void setUranusRise(java.util.Date UranusRise) {
        this.UranusRise = UranusRise;
    }

    public java.util.Date getUranusSet() {
        return UranusSet;
    }

    public void setUranusSet(java.util.Date UranusSet) {
        this.UranusSet = UranusSet;
    }

    public java.util.Date getNeptuneRise() {
        return NeptuneRise;
    }

    public void setNeptuneRise(java.util.Date NeptuneRise) {
        this.NeptuneRise = NeptuneRise;
    }

    public java.util.Date getNeptuneSet() {
        return NeptuneSet;
    }

    public void setNeptuneSet(java.util.Date NeptuneSet) {
        this.NeptuneSet = NeptuneSet;
    }

    public java.util.Date getPlutoRise() {
        return PlutoRise;
    }

    public void setPlutoRise(java.util.Date PlutoRise) {
        this.PlutoRise = PlutoRise;
    }

    public java.util.Date getPlutoSet() {
        return PlutoSet;
    }

    public void setPlutoSet(java.util.Date PlutoSet) {
        this.PlutoSet = PlutoSet;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
