package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblrecoveryaccount_question.
 */
public class RecoveryAccountQuestion {

    private Long id;
    private String Question;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RecoveryAccountQuestion() {
    }

    public RecoveryAccountQuestion(Long id) {
        this.id = id;
    }

    public RecoveryAccountQuestion(Long id, String Question) {
        this.id = id;
        this.Question = Question;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getQuestion() {
        return Question;
    }

    public void setQuestion(String Question) {
        this.Question = Question;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString(){
        return this.Question;
    }
    // KEEP METHODS END

}
