package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblsolareclipse.
 */
public class SolarEclipse {

    private Long id;
    private Long ServerId;
    private String RowId;
    private java.util.Date InfoDate;
    private Integer Phase;
    private Double Magnitude;
    private java.util.Date Contact1;
    private java.util.Date Contact2;
    private java.util.Date Contact3;
    private java.util.Date Contact4;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SolarEclipse() {
    }

    public SolarEclipse(Long id) {
        this.id = id;
    }

    public SolarEclipse(Long id, Long ServerId, String RowId, java.util.Date InfoDate, Integer Phase, Double Magnitude, java.util.Date Contact1, java.util.Date Contact2, java.util.Date Contact3, java.util.Date Contact4) {
        this.id = id;
        this.ServerId = ServerId;
        this.RowId = RowId;
        this.InfoDate = InfoDate;
        this.Phase = Phase;
        this.Magnitude = Magnitude;
        this.Contact1 = Contact1;
        this.Contact2 = Contact2;
        this.Contact3 = Contact3;
        this.Contact4 = Contact4;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return ServerId;
    }

    public void setServerId(Long ServerId) {
        this.ServerId = ServerId;
    }

    public String getRowId() {
        return RowId;
    }

    public void setRowId(String RowId) {
        this.RowId = RowId;
    }

    public java.util.Date getInfoDate() {
        return InfoDate;
    }

    public void setInfoDate(java.util.Date InfoDate) {
        this.InfoDate = InfoDate;
    }

    public Integer getPhase() {
        return Phase;
    }

    public void setPhase(Integer Phase) {
        this.Phase = Phase;
    }

    public Double getMagnitude() {
        return Magnitude;
    }

    public void setMagnitude(Double Magnitude) {
        this.Magnitude = Magnitude;
    }

    public java.util.Date getContact1() {
        return Contact1;
    }

    public void setContact1(java.util.Date Contact1) {
        this.Contact1 = Contact1;
    }

    public java.util.Date getContact2() {
        return Contact2;
    }

    public void setContact2(java.util.Date Contact2) {
        this.Contact2 = Contact2;
    }

    public java.util.Date getContact3() {
        return Contact3;
    }

    public void setContact3(java.util.Date Contact3) {
        this.Contact3 = Contact3;
    }

    public java.util.Date getContact4() {
        return Contact4;
    }

    public void setContact4(java.util.Date Contact4) {
        this.Contact4 = Contact4;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
