package com.health.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.health.data.BodyRegion_BodyFeelingType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tblbodyregion_feelingtype.
*/
public class BodyRegion_BodyFeelingTypeDao extends AbstractDao<BodyRegion_BodyFeelingType, Long> {

    public static final String TABLENAME = "tblbodyregion_feelingtype";

    /**
     * Properties of entity BodyRegion_BodyFeelingType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property BodyRegionId = new Property(1, Long.class, "BodyRegionId", false, "bodyregionid");
        public final static Property BodyFeelingTypeId = new Property(2, Long.class, "BodyFeelingTypeId", false, "feelingtypeid");
    };

    private DaoSession daoSession;


    public BodyRegion_BodyFeelingTypeDao(DaoConfig config) {
        super(config);
    }
    
    public BodyRegion_BodyFeelingTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tblbodyregion_feelingtype' (" + //
                "'id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'bodyregionid' INTEGER," + // 1: BodyRegionId
                "'feelingtypeid' INTEGER);"); // 2: BodyFeelingTypeId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblbodyregion_feelingtype_bodyregionid ON tblbodyregion_feelingtype" +
                " (bodyregionid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblbodyregion_feelingtype_feelingtypeid ON tblbodyregion_feelingtype" +
                " (feelingtypeid);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tblbodyregion_feelingtype'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BodyRegion_BodyFeelingType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long BodyRegionId = entity.getBodyRegionId();
        if (BodyRegionId != null) {
            stmt.bindLong(2, BodyRegionId);
        }
 
        Long BodyFeelingTypeId = entity.getBodyFeelingTypeId();
        if (BodyFeelingTypeId != null) {
            stmt.bindLong(3, BodyFeelingTypeId);
        }
    }

    @Override
    protected void attachEntity(BodyRegion_BodyFeelingType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BodyRegion_BodyFeelingType readEntity(Cursor cursor, int offset) {
        BodyRegion_BodyFeelingType entity = new BodyRegion_BodyFeelingType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // BodyRegionId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // BodyFeelingTypeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BodyRegion_BodyFeelingType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBodyRegionId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setBodyFeelingTypeId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BodyRegion_BodyFeelingType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BodyRegion_BodyFeelingType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBodyRegionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getBodyFeelingTypeDao().getAllColumns());
            builder.append(" FROM tblbodyregion_feelingtype T");
            builder.append(" LEFT JOIN tblbodyregion T0 ON T.'bodyregionid'=T0.'id'");
            builder.append(" LEFT JOIN tblbodyfeelingtype T1 ON T.'feelingtypeid'=T1.'id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BodyRegion_BodyFeelingType loadCurrentDeep(Cursor cursor, boolean lock) {
        BodyRegion_BodyFeelingType entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BodyRegion bodyRegion = loadCurrentOther(daoSession.getBodyRegionDao(), cursor, offset);
        entity.setBodyRegion(bodyRegion);
        offset += daoSession.getBodyRegionDao().getAllColumns().length;

        BodyFeelingType bodyFeelingType = loadCurrentOther(daoSession.getBodyFeelingTypeDao(), cursor, offset);
        entity.setBodyFeelingType(bodyFeelingType);

        return entity;    
    }

    public BodyRegion_BodyFeelingType loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BodyRegion_BodyFeelingType> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BodyRegion_BodyFeelingType> list = new ArrayList<BodyRegion_BodyFeelingType>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BodyRegion_BodyFeelingType> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BodyRegion_BodyFeelingType> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
