package com.health.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.health.data.Complaint;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tblcomplaint.
*/
public class ComplaintDao extends AbstractDao<Complaint, Long> {

    public static final String TABLENAME = "tblcomplaint";

    /**
     * Properties of entity Complaint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property ServerId = new Property(1, Long.class, "ServerId", false, "serverid");
        public final static Property RowId = new Property(2, String.class, "RowId", false, "rowid");
        public final static Property UserId = new Property(3, Long.class, "UserId", false, "userid");
        public final static Property StartDate = new Property(4, java.util.Date.class, "StartDate", false, "dt");
        public final static Property Count = new Property(5, Integer.class, "Count", false, "count");
        public final static Property BodyComplaintTypeId = new Property(6, Long.class, "BodyComplaintTypeId", false, "complainttypeid");
        public final static Property CommonFeelingTypeId = new Property(7, Long.class, "CommonFeelingTypeId", false, "commonfeelingtypeid");
    };

    private DaoSession daoSession;


    public ComplaintDao(DaoConfig config) {
        super(config);
    }
    
    public ComplaintDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tblcomplaint' (" + //
                "'id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'serverid' INTEGER UNIQUE ," + // 1: ServerId
                "'rowid' TEXT UNIQUE ," + // 2: RowId
                "'userid' INTEGER," + // 3: UserId
                "'dt' INTEGER," + // 4: StartDate
                "'count' INTEGER," + // 5: Count
                "'complainttypeid' INTEGER," + // 6: BodyComplaintTypeId
                "'commonfeelingtypeid' INTEGER);"); // 7: CommonFeelingTypeId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcomplaint_serverid ON tblcomplaint" +
                " (serverid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcomplaint_userid ON tblcomplaint" +
                " (userid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcomplaint_complainttypeid ON tblcomplaint" +
                " (complainttypeid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcomplaint_commonfeelingtypeid ON tblcomplaint" +
                " (commonfeelingtypeid);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tblcomplaint'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Complaint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long ServerId = entity.getServerId();
        if (ServerId != null) {
            stmt.bindLong(2, ServerId);
        }
 
        String RowId = entity.getRowId();
        if (RowId != null) {
            stmt.bindString(3, RowId);
        }
 
        Long UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindLong(4, UserId);
        }
 
        java.util.Date StartDate = entity.getStartDate();
        if (StartDate != null) {
            stmt.bindLong(5, StartDate.getTime());
        }
 
        Integer Count = entity.getCount();
        if (Count != null) {
            stmt.bindLong(6, Count);
        }
 
        Long BodyComplaintTypeId = entity.getBodyComplaintTypeId();
        if (BodyComplaintTypeId != null) {
            stmt.bindLong(7, BodyComplaintTypeId);
        }
 
        Long CommonFeelingTypeId = entity.getCommonFeelingTypeId();
        if (CommonFeelingTypeId != null) {
            stmt.bindLong(8, CommonFeelingTypeId);
        }
    }

    @Override
    protected void attachEntity(Complaint entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Complaint readEntity(Cursor cursor, int offset) {
        Complaint entity = new Complaint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // ServerId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // RowId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // UserId
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // StartDate
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // Count
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // BodyComplaintTypeId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // CommonFeelingTypeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Complaint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setServerId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setRowId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setStartDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setCount(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setBodyComplaintTypeId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setCommonFeelingTypeId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Complaint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Complaint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBodyComplaintTypeDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCommonFeelingTypeDao().getAllColumns());
            builder.append(" FROM tblcomplaint T");
            builder.append(" LEFT JOIN tblbodycomplainttype T0 ON T.'complainttypeid'=T0.'id'");
            builder.append(" LEFT JOIN tblcommonfeelingtype T1 ON T.'commonfeelingtypeid'=T1.'id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Complaint loadCurrentDeep(Cursor cursor, boolean lock) {
        Complaint entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BodyComplaintType bodyComplaintType = loadCurrentOther(daoSession.getBodyComplaintTypeDao(), cursor, offset);
        entity.setBodyComplaintType(bodyComplaintType);
        offset += daoSession.getBodyComplaintTypeDao().getAllColumns().length;

        CommonFeelingType commonFeelingType = loadCurrentOther(daoSession.getCommonFeelingTypeDao(), cursor, offset);
        entity.setCommonFeelingType(commonFeelingType);

        return entity;    
    }

    public Complaint loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Complaint> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Complaint> list = new ArrayList<Complaint>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Complaint> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Complaint> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
