package com.health.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.health.data.UserBodyFeelingType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tbluserbodyfeelingtype.
*/
public class UserBodyFeelingTypeDao extends AbstractDao<UserBodyFeelingType, Long> {

    public static final String TABLENAME = "tbluserbodyfeelingtype";

    /**
     * Properties of entity UserBodyFeelingType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property ServerId = new Property(1, Long.class, "ServerId", false, "serverid");
        public final static Property RowId = new Property(2, String.class, "RowId", false, "rowid");
        public final static Property UserId = new Property(3, Long.class, "UserId", false, "userid");
        public final static Property Color = new Property(4, Integer.class, "Color", false, "COLOR");
        public final static Property BodyFeelingTypeId = new Property(5, Long.class, "BodyFeelingTypeId", false, "BodyFeelingType_id");
    };

    private DaoSession daoSession;


    public UserBodyFeelingTypeDao(DaoConfig config) {
        super(config);
    }
    
    public UserBodyFeelingTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tbluserbodyfeelingtype' (" + //
                "'id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'serverid' INTEGER UNIQUE ," + // 1: ServerId
                "'rowid' TEXT UNIQUE ," + // 2: RowId
                "'userid' INTEGER," + // 3: UserId
                "'COLOR' INTEGER," + // 4: Color
                "'BodyFeelingType_id' INTEGER);"); // 5: BodyFeelingTypeId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_tbluserbodyfeelingtype_serverid ON tbluserbodyfeelingtype" +
                " (serverid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tbluserbodyfeelingtype_userid ON tbluserbodyfeelingtype" +
                " (userid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tbluserbodyfeelingtype_BodyFeelingType_id ON tbluserbodyfeelingtype" +
                " (BodyFeelingType_id);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tbluserbodyfeelingtype'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserBodyFeelingType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long ServerId = entity.getServerId();
        if (ServerId != null) {
            stmt.bindLong(2, ServerId);
        }
 
        String RowId = entity.getRowId();
        if (RowId != null) {
            stmt.bindString(3, RowId);
        }
 
        Long UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindLong(4, UserId);
        }
 
        Integer Color = entity.getColor();
        if (Color != null) {
            stmt.bindLong(5, Color);
        }
 
        Long BodyFeelingTypeId = entity.getBodyFeelingTypeId();
        if (BodyFeelingTypeId != null) {
            stmt.bindLong(6, BodyFeelingTypeId);
        }
    }

    @Override
    protected void attachEntity(UserBodyFeelingType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserBodyFeelingType readEntity(Cursor cursor, int offset) {
        UserBodyFeelingType entity = new UserBodyFeelingType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // ServerId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // RowId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // UserId
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // Color
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // BodyFeelingTypeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserBodyFeelingType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setServerId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setRowId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setColor(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setBodyFeelingTypeId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserBodyFeelingType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserBodyFeelingType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBodyFeelingTypeDao().getAllColumns());
            builder.append(" FROM tbluserbodyfeelingtype T");
            builder.append(" LEFT JOIN tblbodyfeelingtype T0 ON T.'BodyFeelingType_id'=T0.'id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected UserBodyFeelingType loadCurrentDeep(Cursor cursor, boolean lock) {
        UserBodyFeelingType entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BodyFeelingType bodyFeelingType = loadCurrentOther(daoSession.getBodyFeelingTypeDao(), cursor, offset);
        entity.setBodyFeelingType(bodyFeelingType);

        return entity;    
    }

    public UserBodyFeelingType loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<UserBodyFeelingType> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<UserBodyFeelingType> list = new ArrayList<UserBodyFeelingType>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<UserBodyFeelingType> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<UserBodyFeelingType> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
