INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(1, 'боль сжимающая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(2, 'боль давящая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(3, 'боль пульсирующая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(4, 'ощущение «тяжелой» головы');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(5, 'боль острая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(6, 'боль ноющая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(7, 'боль тупая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(8, 'боль жгучая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(9, 'боль зудящая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(10, 'головокружение');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(11, 'мелькание "мушек" перед глазами');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(12, 'боль на яркий свет');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(13, 'потемнение');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(14, 'снижение остроты зрения');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(15, 'боль при жевании');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(16, 'сухость');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(17, 'отечность');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(18, 'затрудненное дыхание');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(19, 'боль при глотании');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(20, 'першение');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(21, 'онемение');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(22, 'боль  колющая');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(23, 'шум');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(24, 'нарушение слуха');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(25, 'чувство заложенности');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(26, 'напряжение мышц');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(27, 'чувство сжатия');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(28, 'затрудненный вдох');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(29, 'затрудненный выдох');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(30, 'чувство нехватки воздуха');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(31, 'изжога');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(32, 'чувство тяжести');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(33, 'вздутие');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(34, 'тугоподвижность');
INSERT INTO `tblbodyfeelingtype` (`id`, `name`) VALUES(35, 'чувство холода');