INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(1, 'Afghanistan', 'af', 'afg', 'Афганистан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(2, 'Aland Islands', 'ax', 'ala', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(3, 'Albania', 'al', 'alb', 'Албания');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(4, 'Algeria', 'dz', 'dza', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(5, 'American Samoa', 'as', 'asm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(6, 'Andorra', 'ad', 'and', 'Андорра');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(7, 'Angola', 'ao', 'ago', 'Ангола');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(8, 'Anguilla', 'ai', 'aia', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(9, 'Antarctica', 'aq', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(10, 'Antigua and Barbuda', 'ag', 'atg', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(11, 'Argentina', 'ar', 'arg', 'Аргентина');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(12, 'Armenia', 'am', 'arm', 'Армения');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(13, 'Aruba', 'aw', 'abw', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(14, 'Australia', 'au', 'aus', 'Австралия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(15, 'Austria', 'at', 'aut', 'Австрия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(16, 'Azerbaijan', 'az', 'aze', 'Азербайджан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(17, 'Bahamas', 'bs', 'bhs', 'Багамы');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(18, 'Bahrain', 'bh', 'bhr', 'Бахрейн');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(19, 'Bangladesh', 'bd', 'bgd', 'Бангладеш');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(20, 'Barbados', 'bb', 'brb', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(21, 'Belarus', 'by', 'blr', 'Беларусь');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(22, 'Belgium', 'be', 'bel', 'Бельгия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(23, 'Belize', 'bz', 'blz', 'Белиз');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(24, 'Benin', 'bj', 'ben', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(25, 'Bermuda', 'bm', 'bmu', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(26, 'Bhutan', 'bt', 'btn', 'Бутан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(27, 'Bolivia, Plurinational State of', 'bo', 'bol', 'Боливия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(28, 'Bonaire, Sint Eustatius and Saba', 'bq', 'bes', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(29, 'Bosnia and Herzegovina', 'ba', 'bih', 'Босния и Герцеговина');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(30, 'Botswana', 'bw', 'bwa', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(31, 'Bouvet Island', 'bv', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(32, 'Brazil', 'br', 'bra', 'Бразилия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(33, 'British Indian Ocean Territory', 'io', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(34, 'Brunei Darussalam', 'bn', 'brn', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(35, 'Bulgaria', 'bg', 'bgr', 'Болгария');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(36, 'Burkina Faso', 'bf', 'bfa', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(37, 'Burundi', 'bi', 'bdi', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(38, 'Cambodia', 'kh', 'khm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(39, 'Cameroon', 'cm', 'cmr', 'Камерун');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(40, 'Canada', 'ca', 'can', 'Канада');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(41, 'Cape Verde', 'cv', 'cpv', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(42, 'Cayman Islands', 'ky', 'cym', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(43, 'Central African Republic', 'cf', 'caf', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(44, 'Chad', 'td', 'tcd', 'Чад');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(45, 'Chile', 'cl', 'chl', 'Чили');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(46, 'China', 'cn', 'chn', 'Китай');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(47, 'Christmas Island', 'cx', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(48, 'Cocos (Keeling) Islands', 'cc', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(49, 'Colombia', 'co', 'col', 'Колумбия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(50, 'Comoros', 'km', 'com', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(51, 'Congo', 'cg', 'cog', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(52, 'Congo, The Democratic Republic of the', 'cd', 'cod', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(53, 'Cook Islands', 'ck', 'cok', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(54, 'Costa Rica', 'cr', 'cri', 'Коста-Рика');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(55, 'Cote d''Ivoire', 'ci', 'civ', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(56, 'Croatia', 'hr', 'hrv', 'Хорватия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(57, 'Cuba', 'cu', 'cub', 'Куба');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(58, 'Curacao', 'cw', 'cuw', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(59, 'Cyprus', 'cy', 'cyp', 'Кипр');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(60, 'Czech Republic', 'cz', 'cze', 'Чехия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(61, 'Denmark', 'dk', 'dnk', 'Дания');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(62, 'Djibouti', 'dj', 'dji', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(63, 'Dominica', 'dm', 'dma', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(64, 'Dominican Republic', 'do', 'dom', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(65, 'Ecuador', 'ec', 'ecu', 'Эквадор');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(66, 'Egypt', 'eg', 'egy', 'Египт');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(67, 'El Salvador', 'sv', 'slv', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(68, 'Equatorial Guinea', 'gq', 'gnq', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(69, 'Eritrea', 'er', 'eri', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(70, 'Estonia', 'ee', 'est', 'Эстония');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(71, 'Ethiopia', 'et', 'eth', 'Эфиопия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(72, 'Falkland Islands (Malvinas)', 'fk', 'flk', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(73, 'Faroe Islands', 'fo', 'fro', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(74, 'Fiji', 'fj', 'fji', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(75, 'Finland', 'fi', 'fin', 'Финляндия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(76, 'France', 'fr', 'fra', 'Франция');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(77, 'French Guiana', 'gf', 'guf', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(78, 'French Polynesia', 'pf', 'pyf', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(79, 'French Southern Territories', 'tf', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(80, 'Gabon', 'ga', 'gab', 'Габон');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(81, 'Gambia', 'gm', 'gmb', 'Гамбия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(82, 'Georgia', 'ge', 'geo', 'Грузия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(83, 'Germany', 'de', 'deu', 'Германия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(84, 'Ghana', 'gh', 'gha', 'Гана');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(85, 'Gibraltar', 'gi', 'gib', 'Гибралтар');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(86, 'Greece', 'gr', 'grc', 'Греция');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(87, 'Greenland', 'gl', 'grl', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(88, 'Grenada', 'gd', 'grd', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(89, 'Guadeloupe', 'gp', 'glp', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(90, 'Guam', 'gu', 'gum', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(91, 'Guatemala', 'gt', 'gtm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(92, 'Guernsey', 'gg', 'ggy', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(93, 'Guinea', 'gn', 'gin', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(94, 'Guinea-Bissau', 'gw', 'gnb', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(95, 'Guyana', 'gy', 'guy', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(96, 'Haiti', 'ht', 'hti', 'Гаити');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(97, 'Heard Island and McDonald Islands', 'hm', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(98, 'Holy See (Vatican City State)', 'va', 'vat', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(99, 'Honduras', 'hn', 'hnd', 'Гондурас');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(100, 'Hong Kong', 'hk', 'hkg', 'Гон-Конг');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(101, 'Hungary', 'hu', 'hun', 'Венгрия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(102, 'Iceland', 'is', 'isl', 'Исландия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(103, 'India', 'in', 'ind', 'Индия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(104, 'Indonesia', 'id', 'idn', 'Индонезия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(105, 'Iran, Islamic Republic of', 'ir', 'irn', 'Иран');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(106, 'Iraq', 'iq', 'irq', 'Ирак');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(107, 'Ireland', 'ie', 'irl', 'Ирландия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(108, 'Isle of Man', 'im', 'imn', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(109, 'Israel', 'il', 'isr', 'Израиль');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(110, 'Italy', 'it', 'ita', 'Италия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(111, 'Jamaica', 'jm', 'jam', 'Ямайка');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(112, 'Japan', 'jp', 'jpn', 'Япония');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(113, 'Jersey', 'je', 'jey', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(114, 'Jordan', 'jo', 'jor', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(115, 'Kazakhstan', 'kz', 'kaz', 'Казахстан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(116, 'Kenya', 'ke', 'ken', 'Кения');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(117, 'Kiribati', 'ki', 'kir', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(118, 'Korea, Democratic People''s Republic of', 'kp', 'prk', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(119, 'Korea, Republic of', 'kr', 'kor', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(120, 'Kuwait', 'kw', 'kwt', 'Кувейт');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(121, 'Kyrgyzstan', 'kg', 'kgz', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(122, 'Lao People''s Democratic Republic', 'la', 'lao', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(123, 'Latvia', 'lv', 'lva', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(124, 'Lebanon', 'lb', 'lbn', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(125, 'Lesotho', 'ls', 'lso', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(126, 'Liberia', 'lr', 'lbr', 'Либерия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(127, 'Libyan Arab Jamahiriya', 'ly', 'lby', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(128, 'Liechtenstein', 'li', 'lie', 'Лихтенштейн');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(129, 'Lithuania', 'lt', 'ltu', 'Литва');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(130, 'Luxembourg', 'lu', 'lux', 'Люксембург');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(131, 'Macao', 'mo', 'mac', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(132, 'Macedonia, The former Yugoslav Republic of', 'mk', 'mkd', 'Македония');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(133, 'Madagascar', 'mg', 'mdg', 'Магадаскар');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(134, 'Malawi', 'mw', 'mwi', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(135, 'Malaysia', 'my', 'mys', 'Малайзия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(136, 'Maldives', 'mv', 'mdv', 'Мальдивы');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(137, 'Mali', 'ml', 'mli', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(138, 'Malta', 'mt', 'mlt', 'Мальта');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(139, 'Marshall Islands', 'mh', 'mhl', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(140, 'Martinique', 'mq', 'mtq', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(141, 'Mauritania', 'mr', 'mrt', 'Мавритания');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(142, 'Mauritius', 'mu', 'mus', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(143, 'Mayotte', 'yt', 'myt', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(144, 'Mexico', 'mx', 'mex', 'Мексика');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(145, 'Micronesia, Federated States of', 'fm', 'fsm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(146, 'Moldova, Republic of', 'md', 'mda', 'Молдова');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(147, 'Monaco', 'mc', 'mco', 'Монако');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(148, 'Mongolia', 'mn', 'mng', 'Монголия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(149, 'Montenegro', 'me', 'mne', 'Черногория');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(150, 'Montserrat', 'ms', 'msr', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(151, 'Morocco', 'ma', 'mar', 'Марокко');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(152, 'Mozambique', 'mz', 'moz', 'Мозамбик');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(153, 'Myanmar', 'mm', 'mmr', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(154, 'Namibia', 'na', 'nam', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(155, 'Nauru', 'nr', 'nru', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(156, 'Nepal', 'np', 'npl', 'Непал');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(157, 'Netherlands', 'nl', 'nld', 'Нидерланды');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(158, 'New Caledonia', 'nc', 'ncl', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(159, 'New Zealand', 'nz', 'nzl', 'Новая зеландия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(160, 'Nicaragua', 'ni', 'nic', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(161, 'Niger', 'ne', 'ner', 'Нигер');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(162, 'Nigeria', 'ng', 'nga', 'Нигерия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(163, 'Niue', 'nu', 'niu', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(164, 'Norfolk Island', 'nf', 'nfk', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(165, 'Northern Mariana Islands', 'mp', 'mnp', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(166, 'Norway', 'no', 'nor', 'Норвегия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(167, 'Oman', 'om', 'omn', 'Оман');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(168, 'Pakistan', 'pk', 'pak', 'Пакистан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(169, 'Palau', 'pw', 'plw', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(170, 'Palestinian Territory, Occupied', 'ps', 'pse', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(171, 'Panama', 'pa', 'pan', 'Панама');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(172, 'Papua New Guinea', 'pg', 'png', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(173, 'Paraguay', 'py', 'pry', 'Парагвай');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(174, 'Peru', 'pe', 'per', 'Перу');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(175, 'Philippines', 'ph', 'phl', 'Филипины');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(176, 'Pitcairn', 'pn', 'pcn', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(177, 'Poland', 'pl', 'pol', 'Польша');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(178, 'Portugal', 'pt', 'prt', 'Португалия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(179, 'Puerto Rico', 'pr', 'pri', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(180, 'Qatar', 'qa', 'qat', 'Катар');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(181, 'Reunion', 're', 'reu', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(182, 'Romania', 'ro', 'rou', 'Румыния');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(183, 'Russian Federation', 'ru', 'rus', 'Россия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(184, 'Rwanda', 'rw', 'rwa', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(185, 'Saint Barthelemy', 'bl', 'blm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(186, 'Saint Helena, Ascension and Tristan Da Cunha', 'sh', 'shn', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(187, 'Saint Kitts and Nevis', 'kn', 'kna', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(188, 'Saint Lucia', 'lc', 'lca', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(189, 'Saint Martin (French Part)', 'mf', 'maf', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(190, 'Saint Pierre and Miquelon', 'pm', 'spm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(191, 'Saint Vincent and The Grenadines', 'vc', 'vct', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(192, 'Samoa', 'ws', 'wsm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(193, 'San Marino', 'sm', 'smr', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(194, 'Sao Tome and Principe', 'st', 'stp', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(195, 'Saudi Arabia', 'sa', 'sau', 'Саудовская Аравия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(196, 'Senegal', 'sn', 'sen', 'Сенегал');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(197, 'Serbia', 'rs', 'srb', 'Сербия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(198, 'Seychelles', 'sc', 'syc', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(199, 'Sierra Leone', 'sl', 'sle', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(200, 'Singapore', 'sg', 'sgp', 'Сингапур');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(201, 'Sint Maarten (Dutch Part)', 'sx', 'sxm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(202, 'Slovakia', 'sk', 'svk', 'Словакия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(203, 'Slovenia', 'si', 'svn', 'Словения');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(204, 'Solomon Islands', 'sb', 'slb', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(205, 'Somalia', 'so', 'som', 'Сомали');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(206, 'South Africa', 'za', 'zaf', 'ЮАР');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(207, 'South Georgia and The South Sandwich Islands', 'gs', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(208, 'South Sudan', 'ss', 'ssd', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(209, 'Spain', 'es', 'esp', 'Испания');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(210, 'Sri Lanka', 'lk', 'lka', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(211, 'Sudan', 'sd', 'sdn', 'Судан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(212, 'Suriname', 'sr', 'sur', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(213, 'Svalbard and Jan Mayen', 'sj', 'sjm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(214, 'Swaziland', 'sz', 'swz', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(215, 'Sweden', 'se', 'swe', 'Швеция');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(216, 'Switzerland', 'ch', 'che', 'Швейцария');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(217, 'Syrian Arab Republic', 'sy', 'syr', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(218, 'Taiwan, Province of China', 'tw', '', 'Тайвань');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(219, 'Tajikistan', 'tj', 'tjk', 'Таджикистан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(220, 'Tanzania, United Republic of', 'tz', 'tza', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(221, 'Thailand', 'th', 'tha', 'Тайланд');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(222, 'Timor-Leste', 'tl', 'tls', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(223, 'Togo', 'tg', 'tgo', 'Того');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(224, 'Tokelau', 'tk', 'tkl', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(225, 'Tonga', 'to', 'ton', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(226, 'Trinidad and Tobago', 'tt', 'tto', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(227, 'Tunisia', 'tn', 'tun', 'Тунис');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(228, 'Turkey', 'tr', 'tur', 'Турция');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(229, 'Turkmenistan', 'tm', 'tkm', 'Туркменистан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(230, 'Turks and Caicos Islands', 'tc', 'tca', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(231, 'Tuvalu', 'tv', 'tuv', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(232, 'Uganda', 'ug', 'uga', 'Уганда');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(233, 'Ukraine', 'ua', 'ukr', 'Украина');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(234, 'United Arab Emirates', 'ae', 'are', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(235, 'United Kingdom', 'gb', 'gbr', 'Великобритания');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(236, 'United States', 'us', 'usa', 'США');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(237, 'United States Minor Outlying Islands', 'um', '', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(238, 'Uruguay', 'uy', 'ury', 'Уругвай');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(239, 'Uzbekistan', 'uz', 'uzb', 'Узбекистан');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(240, 'Vanuatu', 'vu', 'vut', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(241, 'Venezuela, Bolivarian Republic of', 've', 'ven', 'Венесуэла');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(242, 'Viet Nam', 'vn', 'vnm', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(243, 'Virgin Islands, British', 'vg', 'vgb', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(244, 'Virgin Islands, U.S.', 'vi', 'vir', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(245, 'Wallis and Futuna', 'wf', 'wlf', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(246, 'Western Sahara', 'eh', 'esh', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(247, 'Yemen', 'ye', 'yem', NULL);
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(248, 'Zambia', 'zm', 'zmb', 'Замбия');
INSERT INTO `tblcountry` (`id`, `name`, `code`, `culture`, `name_ru`) VALUES(249, 'Zimbabwe', 'zw', 'zwe', 'Зимбабве');
