package com.health.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.health.data.CommonFeelingType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tblcommonfeelingtype.
*/
public class CommonFeelingTypeDao extends AbstractDao<CommonFeelingType, Long> {

    public static final String TABLENAME = "tblcommonfeelingtype";

    /**
     * Properties of entity CommonFeelingType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property Name = new Property(1, String.class, "Name", false, "name");
        public final static Property FullName = new Property(2, String.class, "FullName", false, "fullname");
        public final static Property OrdinalNumber = new Property(3, Integer.class, "OrdinalNumber", false, "ordinalnumber");
        public final static Property Status = new Property(4, Integer.class, "Status", false, "status");
        public final static Property UnitDimensionId = new Property(5, Long.class, "UnitDimensionId", false, "unitid");
        public final static Property CommonFeelingGroupId = new Property(6, Long.class, "CommonFeelingGroupId", false, "feelinggroupid");
    };

    private DaoSession daoSession;


    public CommonFeelingTypeDao(DaoConfig config) {
        super(config);
    }
    
    public CommonFeelingTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tblcommonfeelingtype' (" + //
                "'id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'name' TEXT," + // 1: Name
                "'fullname' TEXT," + // 2: FullName
                "'ordinalnumber' INTEGER," + // 3: OrdinalNumber
                "'status' INTEGER," + // 4: Status
                "'unitid' INTEGER," + // 5: UnitDimensionId
                "'feelinggroupid' INTEGER);"); // 6: CommonFeelingGroupId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcommonfeelingtype_unitid ON tblcommonfeelingtype" +
                " (unitid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcommonfeelingtype_feelinggroupid ON tblcommonfeelingtype" +
                " (feelinggroupid);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tblcommonfeelingtype'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CommonFeelingType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(2, Name);
        }
 
        String FullName = entity.getFullName();
        if (FullName != null) {
            stmt.bindString(3, FullName);
        }
 
        Integer OrdinalNumber = entity.getOrdinalNumber();
        if (OrdinalNumber != null) {
            stmt.bindLong(4, OrdinalNumber);
        }
 
        Integer Status = entity.getStatus();
        if (Status != null) {
            stmt.bindLong(5, Status);
        }
 
        Long UnitDimensionId = entity.getUnitDimensionId();
        if (UnitDimensionId != null) {
            stmt.bindLong(6, UnitDimensionId);
        }
 
        Long CommonFeelingGroupId = entity.getCommonFeelingGroupId();
        if (CommonFeelingGroupId != null) {
            stmt.bindLong(7, CommonFeelingGroupId);
        }
    }

    @Override
    protected void attachEntity(CommonFeelingType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CommonFeelingType readEntity(Cursor cursor, int offset) {
        CommonFeelingType entity = new CommonFeelingType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // FullName
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // OrdinalNumber
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // Status
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // UnitDimensionId
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // CommonFeelingGroupId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CommonFeelingType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFullName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOrdinalNumber(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setStatus(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setUnitDimensionId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setCommonFeelingGroupId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CommonFeelingType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CommonFeelingType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUnitDimensionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCommonFeelingGroupDao().getAllColumns());
            builder.append(" FROM tblcommonfeelingtype T");
            builder.append(" LEFT JOIN tblunitdimension T0 ON T.'unitid'=T0.'id'");
            builder.append(" LEFT JOIN tblcommonfeelinggroup T1 ON T.'feelinggroupid'=T1.'id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CommonFeelingType loadCurrentDeep(Cursor cursor, boolean lock) {
        CommonFeelingType entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        UnitDimension unitDimension = loadCurrentOther(daoSession.getUnitDimensionDao(), cursor, offset);
        entity.setUnitDimension(unitDimension);
        offset += daoSession.getUnitDimensionDao().getAllColumns().length;

        CommonFeelingGroup commonFeelingGroup = loadCurrentOther(daoSession.getCommonFeelingGroupDao(), cursor, offset);
        entity.setCommonFeelingGroup(commonFeelingGroup);

        return entity;    
    }

    public CommonFeelingType loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CommonFeelingType> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CommonFeelingType> list = new ArrayList<CommonFeelingType>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CommonFeelingType> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CommonFeelingType> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
