package com.health.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.health.data.CustomFactorType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tblcustomfactortype.
*/
public class CustomFactorTypeDao extends AbstractDao<CustomFactorType, Long> {

    public static final String TABLENAME = "tblcustomfactortype";

    /**
     * Properties of entity CustomFactorType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property ServerId = new Property(1, Long.class, "ServerId", false, "serverid");
        public final static Property RowId = new Property(2, String.class, "RowId", false, "rowid");
        public final static Property UserId = new Property(3, Long.class, "UserId", false, "userid");
        public final static Property Name = new Property(4, String.class, "Name", false, "name");
        public final static Property FullName = new Property(5, String.class, "FullName", false, "fullname");
        public final static Property OrdinalNumber = new Property(6, Integer.class, "OrdinalNumber", false, "ordinalnumber");
        public final static Property Status = new Property(7, Integer.class, "Status", false, "status");
        public final static Property UnitDimensionId = new Property(8, Long.class, "UnitDimensionId", false, "unitid");
        public final static Property FactorGroupId = new Property(9, Long.class, "FactorGroupId", false, "factorgroupid");
    };

    private DaoSession daoSession;


    public CustomFactorTypeDao(DaoConfig config) {
        super(config);
    }
    
    public CustomFactorTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tblcustomfactortype' (" + //
                "'id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'serverid' INTEGER UNIQUE ," + // 1: ServerId
                "'rowid' TEXT UNIQUE ," + // 2: RowId
                "'userid' INTEGER," + // 3: UserId
                "'name' TEXT," + // 4: Name
                "'fullname' TEXT," + // 5: FullName
                "'ordinalnumber' INTEGER," + // 6: OrdinalNumber
                "'status' INTEGER," + // 7: Status
                "'unitid' INTEGER," + // 8: UnitDimensionId
                "'factorgroupid' INTEGER);"); // 9: FactorGroupId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcustomfactortype_serverid ON tblcustomfactortype" +
                " (serverid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcustomfactortype_userid ON tblcustomfactortype" +
                " (userid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcustomfactortype_unitid ON tblcustomfactortype" +
                " (unitid);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_tblcustomfactortype_factorgroupid ON tblcustomfactortype" +
                " (factorgroupid);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tblcustomfactortype'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CustomFactorType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long ServerId = entity.getServerId();
        if (ServerId != null) {
            stmt.bindLong(2, ServerId);
        }
 
        String RowId = entity.getRowId();
        if (RowId != null) {
            stmt.bindString(3, RowId);
        }
 
        Long UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindLong(4, UserId);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(5, Name);
        }
 
        String FullName = entity.getFullName();
        if (FullName != null) {
            stmt.bindString(6, FullName);
        }
 
        Integer OrdinalNumber = entity.getOrdinalNumber();
        if (OrdinalNumber != null) {
            stmt.bindLong(7, OrdinalNumber);
        }
 
        Integer Status = entity.getStatus();
        if (Status != null) {
            stmt.bindLong(8, Status);
        }
 
        Long UnitDimensionId = entity.getUnitDimensionId();
        if (UnitDimensionId != null) {
            stmt.bindLong(9, UnitDimensionId);
        }
 
        Long FactorGroupId = entity.getFactorGroupId();
        if (FactorGroupId != null) {
            stmt.bindLong(10, FactorGroupId);
        }
    }

    @Override
    protected void attachEntity(CustomFactorType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CustomFactorType readEntity(Cursor cursor, int offset) {
        CustomFactorType entity = new CustomFactorType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // ServerId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // RowId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // UserId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // FullName
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // OrdinalNumber
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // Status
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // UnitDimensionId
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9) // FactorGroupId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CustomFactorType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setServerId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setRowId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFullName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setOrdinalNumber(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setStatus(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setUnitDimensionId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setFactorGroupId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CustomFactorType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CustomFactorType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUnitDimensionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getFactorGroupDao().getAllColumns());
            builder.append(" FROM tblcustomfactortype T");
            builder.append(" LEFT JOIN tblunitdimension T0 ON T.'unitid'=T0.'id'");
            builder.append(" LEFT JOIN tblfactorgroup T1 ON T.'factorgroupid'=T1.'id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CustomFactorType loadCurrentDeep(Cursor cursor, boolean lock) {
        CustomFactorType entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        UnitDimension unitDimension = loadCurrentOther(daoSession.getUnitDimensionDao(), cursor, offset);
        entity.setUnitDimension(unitDimension);
        offset += daoSession.getUnitDimensionDao().getAllColumns().length;

        FactorGroup factorGroup = loadCurrentOther(daoSession.getFactorGroupDao(), cursor, offset);
        entity.setFactorGroup(factorGroup);

        return entity;    
    }

    public CustomFactorType loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CustomFactorType> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CustomFactorType> list = new ArrayList<CustomFactorType>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CustomFactorType> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CustomFactorType> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
