package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblgeophysicshourly.
 */
public class GeoPhysics {

    private Long id;
    private Long ServerId;
    private String RowId;
    private java.util.Date InfoDate;
    private Integer KpId;
    private Integer Ap;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GeoPhysics() {
    }

    public GeoPhysics(Long id) {
        this.id = id;
    }

    public GeoPhysics(Long id, Long ServerId, String RowId, java.util.Date InfoDate, Integer KpId, Integer Ap) {
        this.id = id;
        this.ServerId = ServerId;
        this.RowId = RowId;
        this.InfoDate = InfoDate;
        this.KpId = KpId;
        this.Ap = Ap;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return ServerId;
    }

    public void setServerId(Long ServerId) {
        this.ServerId = ServerId;
    }

    public String getRowId() {
        return RowId;
    }

    public void setRowId(String RowId) {
        this.RowId = RowId;
    }

    public java.util.Date getInfoDate() {
        return InfoDate;
    }

    public void setInfoDate(java.util.Date InfoDate) {
        this.InfoDate = InfoDate;
    }

    public Integer getKpId() {
        return KpId;
    }

    public void setKpId(Integer KpId) {
        this.KpId = KpId;
    }

    public Integer getAp() {
        return Ap;
    }

    public void setAp(Integer Ap) {
        this.Ap = Ap;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
