package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblmoonphase.
 */
public class MoonPhase {

    private Long id;
    private Long ServerId;
    private String RowId;
    private java.util.Date InfoDate;
    private String MoonPhase;
    private Long MoonPhaseId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MoonPhase() {
    }

    public MoonPhase(Long id) {
        this.id = id;
    }

    public MoonPhase(Long id, Long ServerId, String RowId, java.util.Date InfoDate, String MoonPhase, Long MoonPhaseId) {
        this.id = id;
        this.ServerId = ServerId;
        this.RowId = RowId;
        this.InfoDate = InfoDate;
        this.MoonPhase = MoonPhase;
        this.MoonPhaseId = MoonPhaseId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return ServerId;
    }

    public void setServerId(Long ServerId) {
        this.ServerId = ServerId;
    }

    public String getRowId() {
        return RowId;
    }

    public void setRowId(String RowId) {
        this.RowId = RowId;
    }

    public java.util.Date getInfoDate() {
        return InfoDate;
    }

    public void setInfoDate(java.util.Date InfoDate) {
        this.InfoDate = InfoDate;
    }

    public String getMoonPhase() {
        return MoonPhase;
    }

    public void setMoonPhase(String MoonPhase) {
        this.MoonPhase = MoonPhase;
    }

    public Long getMoonPhaseId() {
        return MoonPhaseId;
    }

    public void setMoonPhaseId(Long MoonPhaseId) {
        this.MoonPhaseId = MoonPhaseId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
