package com.health.data;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.health.data.OperationUserData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tbloperationuserdata.
*/
public class OperationUserDataDao extends AbstractDao<OperationUserData, Long> {

    public static final String TABLENAME = "tbloperationuserdata";

    /**
     * Properties of entity OperationUserData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property ClientId = new Property(1, Long.class, "ClientId", false, "CLIENT_ID");
        public final static Property ServerId = new Property(2, Long.class, "ServerId", false, "SERVER_ID");
        public final static Property OperationType = new Property(3, Integer.class, "OperationType", false, "OPERATION_TYPE");
        public final static Property TableId = new Property(4, Integer.class, "TableId", false, "TABLE_ID");
        public final static Property OperationDate = new Property(5, java.util.Date.class, "OperationDate", false, "OPERATION_DATE");
        public final static Property RowId = new Property(6, String.class, "RowId", false, "ROW_ID");
        public final static Property UserId = new Property(7, Long.class, "UserId", false, "user_id");
    };

    private DaoSession daoSession;


    public OperationUserDataDao(DaoConfig config) {
        super(config);
    }
    
    public OperationUserDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tbloperationuserdata' (" + //
                "'id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'CLIENT_ID' INTEGER," + // 1: ClientId
                "'SERVER_ID' INTEGER," + // 2: ServerId
                "'OPERATION_TYPE' INTEGER," + // 3: OperationType
                "'TABLE_ID' INTEGER," + // 4: TableId
                "'OPERATION_DATE' INTEGER," + // 5: OperationDate
                "'ROW_ID' TEXT," + // 6: RowId
                "'user_id' INTEGER);"); // 7: UserId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_tbloperationuserdata_user_id ON tbloperationuserdata" +
                " (user_id);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tbloperationuserdata'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, OperationUserData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long ClientId = entity.getClientId();
        if (ClientId != null) {
            stmt.bindLong(2, ClientId);
        }
 
        Long ServerId = entity.getServerId();
        if (ServerId != null) {
            stmt.bindLong(3, ServerId);
        }
 
        Integer OperationType = entity.getOperationType();
        if (OperationType != null) {
            stmt.bindLong(4, OperationType);
        }
 
        Integer TableId = entity.getTableId();
        if (TableId != null) {
            stmt.bindLong(5, TableId);
        }
 
        java.util.Date OperationDate = entity.getOperationDate();
        if (OperationDate != null) {
            stmt.bindLong(6, OperationDate.getTime());
        }
 
        String RowId = entity.getRowId();
        if (RowId != null) {
            stmt.bindString(7, RowId);
        }
 
        Long UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindLong(8, UserId);
        }
    }

    @Override
    protected void attachEntity(OperationUserData entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public OperationUserData readEntity(Cursor cursor, int offset) {
        OperationUserData entity = new OperationUserData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // ClientId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // ServerId
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // OperationType
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // TableId
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // OperationDate
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // RowId
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // UserId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, OperationUserData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClientId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setServerId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setOperationType(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setTableId(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setOperationDate(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setRowId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUserId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(OperationUserData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(OperationUserData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM tbloperationuserdata T");
            builder.append(" LEFT JOIN tbluser T0 ON T.'user_id'=T0.'id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OperationUserData loadCurrentDeep(Cursor cursor, boolean lock) {
        OperationUserData entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setUser(user);

        return entity;    
    }

    public OperationUserData loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OperationUserData> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OperationUserData> list = new ArrayList<OperationUserData>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OperationUserData> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OperationUserData> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
