package com.health.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table tblwinddirections.
 */
public class WindDirectionType {

    private Long id;
    private String Name;
    private String ShortName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public WindDirectionType() {
    }

    public WindDirectionType(Long id) {
        this.id = id;
    }

    public WindDirectionType(Long id, String Name, String ShortName) {
        this.id = id;
        this.Name = Name;
        this.ShortName = ShortName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getShortName() {
        return ShortName;
    }

    public void setShortName(String ShortName) {
        this.ShortName = ShortName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
